linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor