name: Go CD Pipeline

on:
  workflow_run:
    workflows: ["Go CI Pipeline"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Build application
        run: |
          go build -o ./dist/app ./cmd/api
          mkdir -p ./public
          cp ./dist/app ./public/
          # Adicione outros arquivos estáticos se necessário

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          force_orphan: true